import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Article from './components/Article'
import Header from './components/Header'
import Navigation from './components/Navigation'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Blog & News',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="bg-white">
				<Navigation />
				<Header />
				<Article />
				{children}
			</body>
		</html>
	)
}
